spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"  # React app running on port 3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
      - id: conversion-service
        uri: http://localhost:8081
        predicates:
         - Path=/api/v1/gateway/convert
        filters:
        - RewritePath=/api/v1/gateway/(?<action>.*),/api/v1/${action}
      - id: rate-service
        uri: http://localhost:8082
        predicates:
          - Path=/api/v1/gateway/rates
        filters:
        - RewritePath=/api/v1/gateway/(?<action>.*),/api/v1/${action}